// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  PomoJS.Collections.TaskList = (function(_super) {

    __extends(TaskList, _super);

    TaskList.name = 'TaskList';

    function TaskList() {
      return TaskList.__super__.constructor.apply(this, arguments);
    }

    TaskList.prototype.url = '/tasks';

    TaskList.prototype.model = PomoJS.Models.Task;

    TaskList.prototype.parse = function(response) {
      return response.tasks;
    };

    return TaskList;

  })(Backbone.Collection);

}).call(this);
