// Generated by CoffeeScript 1.3.1
(function() {

  describe('PomoJS.Routers.Router', function() {
    beforeEach(function() {
      this.router = new PomoJS.Routers.Router();
      this.routerSpy = sinon.spy();
      try {
        Backbone.history.start({
          silent: true
        });
      } catch (error) {

      }
      return this.router.navigate("elsewhere");
    });
    it('should exist', function() {
      return expect(PomoJS.Routers.Router).toBeDefined();
    });
    it('should be instantiable', function() {
      var router;
      router = new PomoJS.Routers.Router();
      return expect(router).not.toBeNull();
    });
    return it('fires the index route with a blank hash', function() {
      this.router.on("route:index", this.routerSpy);
      this.router.navigate("", true);
      expect(this.routerSpy.calledOnce).toBeTruthy();
      return expect(this.routerSpy.calledWith()).toBeTruthy();
    });
  });

}).call(this);
