// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  PomoJS.Models.Task = (function(_super) {

    __extends(Task, _super);

    Task.name = 'Task';

    function Task() {
      return Task.__super__.constructor.apply(this, arguments);
    }

    Task.prototype.url = function() {
      var url;
      url = "/tasks";
      if (!this.isNew()) {
        url += "/" + (this.getId());
      }
      return url;
    };

    Task.prototype.defaults = {
      name: '',
      completed: false,
      estimation: 0
    };

    Task.prototype.getId = function() {
      return this.get('id');
    };

    Task.prototype.getName = function() {
      return this.get('name');
    };

    Task.prototype.isCompleted = function() {
      return this.get('completed');
    };

    Task.prototype.getEstimation = function() {
      return this.get('estimation');
    };

    Task.prototype.validate = function(attributes) {
      if (this.getId() < 0) {
        return 'invalid id';
      }
      if (this.getEstimation() < 0) {
        return 'invalid estimation';
      }
    };

    Task.prototype.toJSON = function() {
      return {
        task: this.attributes
      };
    };

    return Task;

  })(Backbone.Model);

}).call(this);
